version: "3.7"
services: 
  database: 
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: projetoCryptos
    volumes:
      - ./api/db/data:/var/libs/mysql
    restart: always
  api: 
    build: "./api"
    container_name: python-container
    environment:
      MYSQL_ROOT_PASSWORD: "projetoCryptos"
    volumes:
      - ./api:/usr/src/app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
